const std = @import("std");
const compiler = @import("zpp_compiler");

fn lower(allocator: std.mem.Allocator, source: []const u8) ![]u8 {
    return compiler.compileToString(allocator, source);
}

test "empty input lowers to header only (no decls)" {
    const a = std.testing.allocator;
    const out = try lower(a, "");
    defer a.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "Generated by zig++") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "@import(\"zpp\")") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "fn ") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "struct ") == null);
}

test "bare main lowers to a multi-line fn body" {
    const a = std.testing.allocator;
    const src = "fn main() !void {}";
    const out = try lower(a, src);
    defer a.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "fn main() !void") != null);
}

test "using lowers to var + defer deinit" {
    const a = std.testing.allocator;
    const src =
        \\fn run() !void {
        \\    using x = try Foo.init();
        \\    _ = x;
        \\}
    ;
    const out = try lower(a, src);
    defer a.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "var x = try Foo.init();") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "defer x.deinit();") != null);
}

test "trait declaration produces a VTable type" {
    const a = std.testing.allocator;
    const src =
        \\trait Writer {
        \\    fn write(self, b: []const u8) !usize;
        \\}
    ;
    const out = try lower(a, src);
    defer a.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "Writer_VTable") != null);
}

test "dyn parameter references zpp.Dyn(VTable)" {
    const a = std.testing.allocator;
    const src =
        \\trait Writer {
        \\    fn write(self, b: []const u8) !usize;
        \\}
        \\fn f(w: dyn Writer) void { _ = w; }
    ;
    const out = try lower(a, src);
    defer a.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "zpp.Dyn(Writer_VTable)") != null);
}

test "multiple using bindings each get their own defer" {
    const a = std.testing.allocator;
    const src =
        \\fn run() !void {
        \\    using a = try A.init();
        \\    using b = try B.init();
        \\    _ = a;
        \\    _ = b;
        \\}
    ;
    const out = try lower(a, src);
    defer a.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "defer a.deinit();") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "defer b.deinit();") != null);
}
