// Generated by zig++ frontend. DO NOT EDIT.
const zpp = @import("zpp");

const Account = struct {
    id: u32,
    name: []const u8,
    // derive(.{ Iterator, Serialize, Compare, FromStr })
    pub fn iter(self: @This()) zpp.derive.Iterator(@This()).FieldIter { return zpp.derive.Iterator(@This()).iter(self); }
    pub fn serialize(self: @This(), allocator: std.mem.Allocator) ![]u8 { return zpp.derive.Serialize(@This()).serialize(self, allocator); }
    pub fn lt(self: @This(), other: @This()) bool { return zpp.derive.Compare(@This()).lt(self, other); }
    pub fn le(self: @This(), other: @This()) bool { return zpp.derive.Compare(@This()).le(self, other); }
    pub fn gt(self: @This(), other: @This()) bool { return zpp.derive.Compare(@This()).gt(self, other); }
    pub fn ge(self: @This(), other: @This()) bool { return zpp.derive.Compare(@This()).ge(self, other); }
    pub fn fromStr(s: []const u8, allocator: std.mem.Allocator) !@This() { return zpp.derive.FromStr(@This()).parse(s, allocator); }
};

