// Generated by zig++ frontend. DO NOT EDIT.
const zpp = @import("zpp");

// trait Greeter
const Greeter_VTable = struct {
    greet: *const fn (ptr: *anyopaque) []const u8,
};
const Greeter = zpp.Dyn(Greeter_VTable);

fn shout(g: zpp.Dyn(Greeter_VTable)) []const u8 {
    return g.greet();
}

