// Generated by zig++ frontend. DO NOT EDIT.
const zpp = @import("zpp");

const std = @import("std");
// effects(.noasync)
fn quiet_hash(bytes: []const u8) u64 {
    var h: u64 = 0xcbf29ce484222325;
    for (bytes) |b| {
        h ^= b;
        h *%= 0x100000001b3;
    }
    return h;
}

fn ask_quiet() []const u8 {
    return "";
}

