// Generated by zig++ frontend. DO NOT EDIT.
const zpp = @import("zpp");

const std = @import("std");
// effects(.custom)
fn fetch() void {
}

fn ask_net() []const u8 {
    return "custom(\"net\")";
}

// effects(.custom)
fn fetch_and_alloc(a: std.mem.Allocator) ![]u8 {
    const buf = try a.alloc(u8, 16);
    return buf;
}

fn ask_net_alloc() []const u8 {
    return "alloc,custom(\"net\")";
}

