// Generated by zig++ frontend. DO NOT EDIT.
const zpp = @import("zpp");

const std = @import("std");
fn run(allocator: std.mem.Allocator) !void {
    var arena = zpp.ArenaScope.init(allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const buf = try a.alloc(u8, 16);
    _ = buf;
}

