// Generated by zig++ frontend. DO NOT EDIT.
const zpp = @import("zpp");

// trait Greeter
const Greeter_VTable = struct {
    greet: *const fn (ptr: *anyopaque) []const u8,
};
const Greeter = zpp.Dyn(Greeter_VTable);

const Hello = struct {
    pub fn greet(self: *@This()) []const u8 {
        _ = self;
        return "hello";
    }
};

// impl Greeter for Hello
fn Greeter_method_greet_Hello(self: *Hello) []const u8 {
    _ = self;
    return "hello";
}
fn Greeter_greet_for_Hello(ptr: *anyopaque) []const u8 {
    const self: *Hello = @ptrCast(@alignCast(ptr));
    return Greeter_method_greet_Hello(self);
}
pub const Greeter_impl_for_Hello: Greeter_VTable = .{
    .greet = Greeter_greet_for_Hello,
};

