// Generated by zig++ frontend. DO NOT EDIT.
const zpp = @import("zpp");

// trait Greeter
const Greeter_VTable = struct {
    name: *const fn (ptr: *anyopaque) []const u8,
    greet: *const fn (ptr: *anyopaque) []const u8,
};
const Greeter = zpp.Dyn(Greeter_VTable);
fn Greeter_default_greet(self: *anyopaque) []const u8 {
    _ = self;

        return "hello from default";
}

const Hello = struct {
    pub fn name(self: *@This()) []const u8 {
        _ = self;
        return "Hello";
    }
};

// impl Greeter for Hello
fn Greeter_method_name_Hello(self: *Hello) []const u8 {
    _ = self;
    return "Hello";
}
fn Greeter_name_for_Hello(ptr: *anyopaque) []const u8 {
    const self: *Hello = @ptrCast(@alignCast(ptr));
    return Greeter_method_name_Hello(self);
}
pub const Greeter_impl_for_Hello: Greeter_VTable = .{
    .name = Greeter_name_for_Hello,
    .greet = Greeter_default_greet,
};

