// Generated by zig++ frontend. DO NOT EDIT.
const zpp = @import("zpp");

// trait Encoder
const Encoder_VTable = struct {
    encode: *const fn (ptr: *anyopaque, a: u32, b: u32, c: u32, d: u32, e: u32, f: u32) u64,
};
const Encoder = zpp.Dyn(Encoder_VTable);

const Fast = struct {
    pub fn encode(self: *@This(), a: u32, b: u32, c: u32, d: u32, e: u32, f: u32) u64 {
        _ = self;
        return @as(u64, a)
            | (@as(u64, b) << 8)
            | (@as(u64, c) << 16)
            | (@as(u64, d) << 24)
            | (@as(u64, e) << 32)
            | (@as(u64, f) << 40);
    }
};

// impl Encoder for Fast
fn Encoder_method_encode_Fast(self: *Fast, a: u32, b: u32, c: u32, d: u32, e: u32, f: u32) u64 {
    _ = self;
    return @as(u64, a)
            | (@as(u64, b) << 8)
            | (@as(u64, c) << 16)
            | (@as(u64, d) << 24)
            | (@as(u64, e) << 32)
            | (@as(u64, f) << 40);
}
fn Encoder_encode_for_Fast(ptr: *anyopaque, a: u32, b: u32, c: u32, d: u32, e: u32, f: u32) u64 {
    const self: *Fast = @ptrCast(@alignCast(ptr));
    return Encoder_method_encode_Fast(self, a, b, c, d, e, f);
}
pub const Encoder_impl_for_Fast: Encoder_VTable = .{
    .encode = Encoder_encode_for_Fast,
};

