//! Helpers for the `build.zpp` thin alias over `build.zig`.
//!
//! When a project has `build.zpp` at its root, `zpp build` will lower it to
//! `build.zig` before invoking `zig build`. The Zig toolchain picks up the
//! generated `build.zig` exactly as it would a hand-written one — there is
//! no other coupling.
//!
//! Detection rule (see `decide`):
//!   - build.zpp present, build.zig absent  -> lower build.zpp -> build.zig
//!   - both present                          -> ignore build.zpp, warn once
//!   - neither / only build.zig              -> unchanged behavior
//!
//! Re-lowering policy: mtime-based. We only rewrite `build.zig` if
//! `build.zpp` is newer (or `build.zig` does not yet exist). The mtime check
//! is simple, dependency-free, and good enough for a developer-facing tool;
//! a hash-based check would require reading both files on every invocation.

const std = @import("std");
const compiler = @import("zpp_compiler");

/// Header prepended to every generated build.zig so users (and tools) can
/// tell at a glance that the file is auto-managed.
pub const generated_header =
    "// Generated by zpp from build.zpp. DO NOT EDIT \xe2\x80\x94 re-run `zpp build`.\n";

pub const Action = enum {
    /// Neither file exists, or only build.zig exists; do nothing special.
    none,
    /// build.zpp exists, build.zig does not: lower.
    lower_fresh,
    /// build.zpp newer than build.zig (and we own build.zig): re-lower.
    relower,
    /// build.zpp older than build.zig: skip lowering, build.zig is up to date.
    skip_up_to_date,
    /// Both files exist but the build.zig is hand-written (no header).
    /// Print one-line warning, do not overwrite.
    ignore_user_build_zig,
};

/// Decide what to do given the on-disk state of `<dir>/build.zpp` and
/// `<dir>/build.zig`. Pure: takes only mtimes + a "has-header" boolean.
pub fn decide(
    have_build_zpp: bool,
    build_zpp_mtime: i128,
    have_build_zig: bool,
    build_zig_mtime: i128,
    build_zig_has_generated_header: bool,
) Action {
    if (!have_build_zpp) return .none;
    if (!have_build_zig) return .lower_fresh;
    if (!build_zig_has_generated_header) return .ignore_user_build_zig;
    if (build_zpp_mtime > build_zig_mtime) return .relower;
    return .skip_up_to_date;
}

/// Read the first line of `path` (truncated to `max_bytes`). Returns an
/// empty slice on any I/O error or if the file is empty. Used to decide
/// whether an existing build.zig was emitted by us.
fn readFirstLine(allocator: std.mem.Allocator, dir: std.fs.Dir, path: []const u8, max_bytes: usize) ![]u8 {
    const data = dir.readFileAlloc(allocator, path, max_bytes) catch |e| switch (e) {
        error.FileNotFound => return try allocator.dupe(u8, ""),
        else => return e,
    };
    defer allocator.free(data);
    const end = std.mem.indexOfScalar(u8, data, '\n') orelse data.len;
    return try allocator.dupe(u8, data[0..end]);
}

/// Returns true if `<dir>/build.zig` starts with our generated_header.
pub fn buildZigIsGenerated(allocator: std.mem.Allocator, dir: std.fs.Dir) bool {
    const line = readFirstLine(allocator, dir, "build.zig", 4096) catch return false;
    defer allocator.free(line);
    // generated_header ends with '\n'; compare against the prefix without that newline.
    const hdr = generated_header[0 .. generated_header.len - 1];
    return std.mem.startsWith(u8, line, hdr);
}

/// Lower a `build.zpp` source string and prepend our generated_header. The
/// caller owns the returned slice. Diagnostics from the compiler are
/// discarded — `compileToString` already does that — keeping this helper a
/// thin wrapper.
pub fn lowerSource(allocator: std.mem.Allocator, source: []const u8) ![]u8 {
    const lowered = try compiler.compileToString(allocator, source);
    defer allocator.free(lowered);
    var out: std.ArrayList(u8) = .{};
    errdefer out.deinit(allocator);
    try out.appendSlice(allocator, generated_header);
    try out.appendSlice(allocator, lowered);
    return out.toOwnedSlice(allocator);
}

/// One-shot driver used by `cmdBuild`:
///   1. Detect build.zpp / build.zig.
///   2. Apply the policy in `decide`.
///   3. Lower + write build.zig if needed.
///
/// `warn` is invoked at most once with a human-readable single-line message
/// (no trailing newline) when build.zpp is shadowed by an existing
/// build.zig. Returns the action that was taken.
pub fn maybeLower(
    allocator: std.mem.Allocator,
    dir: std.fs.Dir,
    warn: *const fn (msg: []const u8) void,
) !Action {
    const zpp_stat = dir.statFile("build.zpp") catch |e| switch (e) {
        error.FileNotFound => return .none,
        else => return e,
    };
    var have_zig: bool = false;
    var zig_mtime: i128 = 0;
    if (dir.statFile("build.zig")) |st| {
        have_zig = true;
        zig_mtime = st.mtime;
    } else |_| {}
    const generated = if (have_zig) buildZigIsGenerated(allocator, dir) else false;

    const action = decide(true, zpp_stat.mtime, have_zig, zig_mtime, generated);

    switch (action) {
        .none, .skip_up_to_date => {},
        .ignore_user_build_zig => {
            warn("zpp: build.zpp ignored because build.zig already exists");
        },
        .lower_fresh, .relower => {
            const source = try dir.readFileAlloc(allocator, "build.zpp", 16 * 1024 * 1024);
            defer allocator.free(source);
            const lowered = try lowerSource(allocator, source);
            defer allocator.free(lowered);
            try dir.writeFile(.{ .sub_path = "build.zig", .data = lowered });
        },
    }
    return action;
}

test "decide policy table" {
    // Neither: nothing to do.
    try std.testing.expectEqual(Action.none, decide(false, 0, false, 0, false));
    try std.testing.expectEqual(Action.none, decide(false, 0, true, 100, true));

    // Only build.zpp.
    try std.testing.expectEqual(Action.lower_fresh, decide(true, 100, false, 0, false));

    // Both, build.zig hand-written.
    try std.testing.expectEqual(Action.ignore_user_build_zig, decide(true, 100, true, 50, false));
    try std.testing.expectEqual(Action.ignore_user_build_zig, decide(true, 50, true, 100, false));

    // Both, build.zig generated and stale.
    try std.testing.expectEqual(Action.relower, decide(true, 200, true, 100, true));
    // Both, build.zig generated and current.
    try std.testing.expectEqual(Action.skip_up_to_date, decide(true, 100, true, 200, true));
    // Both, equal mtime: not stale, treat as up-to-date.
    try std.testing.expectEqual(Action.skip_up_to_date, decide(true, 100, true, 100, true));
}

test "lowerSource prepends header and contains pub fn build(" {
    const a = std.testing.allocator;
    const src =
        \\const std = @import("std");
        \\
        \\pub fn build(b: *std.Build) void {
        \\    _ = b;
        \\}
        \\
    ;
    const out = try lowerSource(a, src);
    defer a.free(out);
    try std.testing.expect(std.mem.startsWith(u8, out, "// Generated by zpp from build.zpp."));
    try std.testing.expect(std.mem.indexOf(u8, out, "pub fn build(") != null);
}

test "buildZigIsGenerated detects header line" {
    const a = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    // No build.zig at all.
    try std.testing.expect(!buildZigIsGenerated(a, tmp.dir));

    // Hand-written file.
    try tmp.dir.writeFile(.{ .sub_path = "build.zig", .data = "const std = @import(\"std\");\n" });
    try std.testing.expect(!buildZigIsGenerated(a, tmp.dir));

    // Generated file.
    try tmp.dir.writeFile(.{
        .sub_path = "build.zig",
        .data = generated_header ++ "const std = @import(\"std\");\n",
    });
    try std.testing.expect(buildZigIsGenerated(a, tmp.dir));
}

test "maybeLower lower_fresh when only build.zpp exists" {
    const a = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const src =
        \\const std = @import("std");
        \\pub fn build(b: *std.Build) void { _ = b; }
        \\
    ;
    try tmp.dir.writeFile(.{ .sub_path = "build.zpp", .data = src });

    const noop = struct {
        fn warn(_: []const u8) void {}
    };
    const action = try maybeLower(a, tmp.dir, &noop.warn);
    try std.testing.expectEqual(Action.lower_fresh, action);

    const written = try tmp.dir.readFileAlloc(a, "build.zig", 64 * 1024);
    defer a.free(written);
    try std.testing.expect(std.mem.startsWith(u8, written, "// Generated by zpp from build.zpp."));
    try std.testing.expect(std.mem.indexOf(u8, written, "pub fn build(") != null);
}

test "maybeLower respects user-written build.zig" {
    const a = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    try tmp.dir.writeFile(.{ .sub_path = "build.zpp", .data = "pub fn build(b: *@import(\"std\").Build) void { _ = b; }\n" });
    const user_zig = "// hand-written\npub fn build(b: *@import(\"std\").Build) void { _ = b; }\n";
    try tmp.dir.writeFile(.{ .sub_path = "build.zig", .data = user_zig });

    var warned: bool = false;
    const W = struct {
        var flag_ptr: *bool = undefined;
        fn warn(_: []const u8) void {
            flag_ptr.* = true;
        }
    };
    W.flag_ptr = &warned;

    const action = try maybeLower(a, tmp.dir, &W.warn);
    try std.testing.expectEqual(Action.ignore_user_build_zig, action);
    try std.testing.expect(warned);

    // build.zig must NOT have been overwritten.
    const after = try tmp.dir.readFileAlloc(a, "build.zig", 64 * 1024);
    defer a.free(after);
    try std.testing.expectEqualStrings(user_zig, after);
}
